## Numpy
A library for matrix computation. Tutorial credit to http://wiki.scipy.org/Tentative_NumPy_Tutorial

In [1]:
import numpy as np

NumPy's main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In Numpy dimensions are called axes. The number of axes is rank.
For example, the coordinates of a point in 3D space [1, 2, 1] is an array of rank 1, because it has one axis. That axis has a length of 3. In example pictured below, the array has rank 2 (it is 2-dimensional). The first dimension (axis) has a length of 2, the second dimension has a length of 3.

In [4]:
np.array([[1, 0, 3], [0, 1, 2]])

array([[1, 0, 3],
       [0, 1, 2]])

### Array creation

In [14]:
#np.zeros(4)
#print np.array([[1,2],[3,4]],dtype=complex)
#print np.linspace(0, 1, num=4)
#print np.arange(0, 1, step=0.25)
#print np.random.random((2,3))
print np.arange(12).reshape(3,4)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### Basic Operations
Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result. Some operations, such as += and *=, act in place to modify an existing array rather than create a new one.

In [15]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
print a, b
print a-b
print b**2
print a > 32
a += 1
print(a)

[20 30 40 50] [0 1 2 3]
[20 29 38 47]
[0 1 4 9]
[False False  True  True]
[21 31 41 51]


Unlike in many matrix languages, the product operator * operates elementwise in NumPy arrays. The matrix product can be performed using the dot function or creating matrix objects.

In [16]:
A = np.array([[1,1], [0,1]])
B = np.array([[2,0], [3,4]])
print A * B
print np.dot(A, B)

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]


### Indexing, Slicing and Iterating
One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences. Format [start:stop:step]

In [23]:
a = np.arange(10)**2+5
a

array([ 5,  6,  9, 14, 21, 30, 41, 54, 69, 86])

In [27]:
a[-2]

69

In [32]:
a[3:10:3]

array([14, 41, 86])

In [34]:
a[::-2]

array([86, 54, 30, 14,  6])

In [ ]:
a[::2]

Multidimensional arrays can have one index per axis. These indices are given in a tuple separated by commas:

In [35]:
b=np.array([[0,1,2,3],[10,11,12,13],[20,21,22,23]])

## equivalent to:
#def f(x,y):
#    return 10*x+y
#b = np.fromfunction(f, (3, 4), dtype=int)

b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])

In [37]:
b[0,2]

2

In [42]:
b[0:3, 0]

array([ 0, 10, 20])

In [43]:
b[ : ,1]

array([ 1, 11, 21])

In [46]:
b[1:3, : ]   

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [47]:
b[-1]

array([20, 21, 22, 23])

Iterating over multidimensional arrays is done with respect to the first axis:

In [50]:
for riga in b:
    print riga

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]


In [52]:
#b.flat
for element in b.flat:
    print element

0
1
2
3
10
11
12
13
20
21
22
23


### Stacking together different arrays
Several arrays can be stacked together along different axes:

In [56]:
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))
print a
print b

[[ 8.  8.]
 [ 4.  9.]]
[[ 3.  5.]
 [ 9.  8.]]


In [57]:
np.vstack((a, b))

array([[ 8.,  8.],
       [ 4.,  9.],
       [ 3.,  5.],
       [ 9.,  8.]])

In [58]:
np.hstack((a, b))

array([[ 8.,  8.,  3.,  5.],
       [ 4.,  9.,  9.,  8.]])

The function column_stack stacks 1D arrays as columns into a 2D array. It is equivalent to vstack only for 1D arrays:

In [59]:
np.column_stack((a,b))  

array([[ 8.,  8.,  3.,  5.],
       [ 4.,  9.,  9.,  8.]])

In [60]:
b = np.array([2., 8.])
np.column_stack((a, b))

array([[ 8.,  8.,  2.],
       [ 4.,  9.,  8.]])